### ISSUE TITLE
Automatic Scraping for Prometheus Operator

### ISSUE THREAD

**Issue by monfardineL** [Stono/kconmon#1]
I've added a service and service monitor for agents, so my Prometheus Operator can automatically detect targets and collect metrics. 
I'm attaching files below, if that could help someone, or even be added to chart.

[agent.zip](https://github.com/Stono/kconmon/files/4894044/agent.zip)

**Comment by lareeth** [comment]
Could you create a PR for this, as I'm looking for this feature too

**Comment by Stono** [comment]
I’m away today but if someone pulls together a PR I’m happy to merge it tomorrow :)

**Comment by monfardineL** [comment]
There it goes [PR 3](https://github.com/Stono/kconmon/pull/3)

**Comment by Stono** [comment]
This is merged and 0.4.0 is released.  Note it's behind a flag which defaults false!
