### ISSUE TITLE
Differences With Blackbox Exporter and Goldpinger?

### ISSUE THREAD

**Issue by supertylerc** [Stono/kconmon#4]
Hi!  First, this project seems great!  I especially like the metadata that is added to indicate things like zones.

What differences exist with this project and something like [bloomberg/goldpinger](https://github.com/bloomberg/goldpinger) and [prometheus/blackbox_exporter](https://github.com/prometheus/blackbox_exporter)?  I can see the service discovery aspects being very valuable compared to Blackbox Exporter, but the differentiator with Goldpinger is not as obvious to me (other than the zone metadata).

Thank you!

**Comment by Stono** [comment]
Hey,
Probably better to ask me questions on twitter or slack than a github issue :)

Someone else recently asked me the same question on twitter.  At the time I wrote this app, I wasn’t aware of goldpinger.  I simply knocked together a tool for my use case.

In hindsight, they’re remarkably similar, however it wouldn’t be fair for me to draw and real pros or cons as I haven’t used goldpinger myself.

Blackbox exporter doesn’t test from every node.  This project is about understanding connectivity from every node on your cluster and segregating that by zone.  It’s a different use case.

Thanks
Karl
