### ISSUE TITLE
Deploy agents on host network

### ISSUE THREAD

**Issue by rmb938** [Stono/kconmon#5]
I think it's useful to have agents also get deployed onto the host network and do the same tests between host network agents.

So we would end up with the following tests:

Host Network -> Host Network
Host Network -> Kubernetes Overlay
Kubernetes Overlay -> Kubernetes Overlay
Kubernetes Overlay -> Host Network

This will allow isolating any problems to only the kubernetes overlay or to the host network or some combination. Maybe also include in the metric labels which type of network (host vs overlay) the agent is on and sending to.

**Comment by Stono** [comment]
@rmb938 how would you propose we do that? You’d have to deploy two agents on every node which doubles the overall cost of the system for just one additional metric

**Comment by rmb938** [comment]
Personally I am ok with deploying 2 agents on every node. I already run a lot of tooling for monitoring and maintaining on every node of my kubernetes clusters so having to run an additional thing with a small overhead is not too much of a big deal for me.

I do find having this type of metric is somewhat important. I have ran into weird network issues where the overlay network seems fine but the host bound traffic has issues going in and out of the overlay.

**Comment by Stono** [comment]
Don’t underestimate the overhead.  All of the requirements scale exponentially with the number of nodes.  

For example if you’ve got 50 nodes, all testing each other just once, that’s 2500 tests, double the number of nodes and you’ll quadruple the number of tests to 10,000.  Multiply that by each of the different tests that run too.  

Not to mention then the doubling of Prometheus metric cardinality (needing to added a network=host|overlay label) to all the Prometheus metrics too.

On my clusters at least (75nodes) that’d be an unacceptable overhead.

**Comment by rmb938** [comment]
Oh right I did not think about all the additional tests and how they would end up scaling.

As much as I would like those metrics I wouldn't want it at the expense of the the testing overhead that you mentioned.
