### ISSUE TITLE
Remove legacy option net.ipv4.tcp_fack

### ISSUE THREAD

**Issue by fahlke** [Stono/kconmon#6]
As stated in [ip-sysctl.txt][1] we can remove the legacy option `tcp_fack`, as it has no effect anymore.

Not only is it a legacy option, but it can also prevent the agents from starting:

```bash
$ kubectl logs kconmon-t9697 -c sysctls
net.core.somaxconn = 32768
net.ipv4.tcp_fin_timeout = 60
net.ipv4.tcp_keepalive_time = 30
net.ipv4.tcp_keepalive_intvl = 30
net.ipv4.tcp_keepalive_probes = 3
sysctl: error: 'net.ipv4.tcp_fack' is an unknown key   # <-- prevents the init container from successful run
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_max_syn_backlog = 3240000
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_sack = 0
```

Tested on EKS with Kubernetes `v1.16.8-eks-fd1ea7`.

[1]: https://www.kernel.org/doc/Documentation/networking/ip-sysctl.txt

**Comment by dimm0** [comment]
I'm getting several errors on some nodes:

```
sysctls sysctl: error: 'net.ipv4.tcp_window_scaling' is an unknown key 
sysctls sysctl: error: 'net.ipv4.tcp_max_syn_backlog' is an unknown key
sysctls sysctl: error: 'net.ipv4.tcp_timestamps' is an unknown key 
sysctls sysctl: error: 'net.ipv4.tcp_sack' is an unknown key 
sysctls sysctl: error: 'net.ipv4.tcp_fack' is an unknown key 
```

This one has 3.10.0-957.el7.x86_64 kernel, unlike others with 5.10

**Comment by Stono** [comment]
@dimm0 for not just turn the kernel tweaks feature off

**Comment by Stono** [comment]
@fahlke v0.4.3 should be released shortly containing this fix!  Thanks for pointing it out.

@dimm0 - i'm not going to support kernel 3.x - and have added a note to the settings to make clear that you should `--set enableTcpTweaks=false` if on <4.

**Comment by dimm0** [comment]
Ok got it
